### ISSUE TITLE
Utilización de labels en el formulario de contacto

### ISSUE THREAD

**Issue by felixzapata** [Comunidades-Tecnologicas/comunidades-tecnologicas.github.io#11]
El formulario de "Get in Touch" no contiene elementos "label" que asocien sus correspondientes campos.

**Comment by ntkog** [comment]
Todavía no habíamos llegado ahí , 

De momento cogimos un template estático rápido para tirar millas, pero si vemos que hay muchas cosas que no molen , y conoces alguna alternativa  que tenga una base mejor, podemos probar más alternativas. No es algo definitivo , y lo bueno es que la funcionalidad del Grid de comunidades si que la hemos hecho nosotros, y no tiene dependencias de ningún tipo y se podría portar fácilmente.

De todas formas feel free para hacer PR sobre cambios que veas necesarios. La idea es que lo hagamos entre todos, y saquemos lo mejor de cada casa.

**Comment by ntkog** [comment]
Merged on b8323c1

gracias @felixzapata !
