### ISSUE TITLE
Niveles de encabezados en página de directorio

### ISSUE THREAD

**Issue by felixzapata** [Comunidades-Tecnologicas/comunidades-tecnologicas.github.io#12]
No sé si se quedarán finalmente los bloques inferiores pero por si acaso para que no se olvide, si no va a haber más encabezados anteriores sugiero cambiar los h3 por h2 para mejorar la jerarquía.

**Comment by ntkog** [comment]
Merged on [b8323c1](https://github.com/Comunidades-Tecnologicas/comunidades-tecnologicas.github.io/commit/b8323c169b17a45d01b574c9fefef12c3fbe4206)

gracias @felixzapata !
