### ISSUE TITLE
Documentación para organizadores

### ISSUE THREAD

**Issue by hhkaos** [Comunidades-Tecnologicas/comunidades-tecnologicas.github.io#4]
En el CLSxMadrid comentamos que sería interesante reunir las guías de comunicación y organización de otras comunidades para reunir las mejores prácticas de cada una de ellas y así aprovecharnos del conocimiento compartido. Incluso la posibilidad de crear una "meta-guía".

A parte (como idea) hemos incluido en este proyecto la posibilidad de crear alguna herramienta que nos permita colaborar a la hora de reunir y mantener actualizado un listado de espacios disponibles para celebrar nuestros eventos con algunas de las características importantes para nosotros a la hora de elegir si es adecuado el sitio o no. Yo he compartido una hoja en un documento de Drive que uso yo con [algunas salas de Madrid](https://docs.google.com/spreadsheets/d/1I9reKooywOG6LNd6J3BLIe1HUZqPCC71D59caqs1hHk/edit#gid=1639906976).

A partir de aquí queda el tema abierto a debate/opiniones/ideas/etc.

**Comment by hhkaos** [comment]
Aprovecho y comparto algunas guías:
* [Guía WordCamp Planning](https://plan.wordcamp.org/)
* [Guía de Iniciador Madrid](https://docs.google.com/document/d/1sPw0eemise5JPEZz1-WCphcdPNB12ZiftHpC80MThvo/edit)
* [GDG Starter guide](https://developers.google.com/groups/start/)

**Comment by jsmanrique** [comment]
Vamos a ir organizando esta info dentro de [su proyecto correspondiente](https://github.com/Comunidades-Tecnologicas/docs). Voy a ir moviendo contenidos y cerramos este ticket si os parece bien

**Comment by jsmanrique** [comment]
Proyecto creado y documentación añadida: https://github.com/Comunidades-Tecnologicas/docs
