### ISSUE TITLE
Contraste de títulos de las comunidades

### ISSUE THREAD

**Issue by felixzapata** [Comunidades-Tecnologicas/comunidades-tecnologicas.github.io#6]
En el directorio de comunidades, los títulos de las mismas que aparecen sobre las pastillas azules tienen un contraste bastante pobre que pueden dificultar su lectura

**Comment by ntkog** [comment]
Gracias por el tip, @felixzapata , 

Corregido en este [commit](https://github.com/Comunidades-Tecnologicas/comunidades-tecnologicas.github.io/commit/fb066b649d6ad950716a1b5f24bfb335d7b1ba10)
